#!/usr/bin/env bash
#Wrapper for emacs to make it better for the terminal.

if [ "$TERM" = "linux" ]; then
    export TERM='xterm'
    echo -en '\e[?8c'
    emacs -nw "$@"
    echo -en '\e[?8c'
else
    emacs -nw "$@"
fi
