#!/usr/bin/env bash

text="$1"
shift 1

fd=3
while [ -e /proc/$$/fd/$fd ] || [ -L /proc/$$/fd/$fd ]; do
    : $(( fd++ ))
    echo $fd
done

eval "exec $fd<&0"

yes "$text" | xargs --arg-file=<(cat <&$fd) "$@"

eval "exec $fd<&-"

